// Generated by CoffeeScript 1.6.1
(function() {

  describe('MarkdownEditingDescriptor', function() {
    describe('save stores the correct data', function() {
      it('saves markdown from markdown editor', function() {
        var saveResult;
        loadFixtures('problem-with-markdown.html');
        this.descriptor = new MarkdownEditingDescriptor($('.problem-editor'));
        saveResult = this.descriptor.save();
        expect(saveResult.metadata.markdown).toEqual('markdown');
        return expect(saveResult.data).toEqual('<problem>\n<p>markdown</p>\n</problem>');
      });
      it('clears markdown when xml editor is selected', function() {
        var saveResult;
        loadFixtures('problem-with-markdown.html');
        this.descriptor = new MarkdownEditingDescriptor($('.problem-editor'));
        this.descriptor.createXMLEditor('replace with markdown');
        saveResult = this.descriptor.save();
        expect(saveResult.nullout).toEqual(['markdown']);
        return expect(saveResult.data).toEqual('replace with markdown');
      });
      return it('saves xml from the xml editor', function() {
        var saveResult;
        loadFixtures('problem-without-markdown.html');
        this.descriptor = new MarkdownEditingDescriptor($('.problem-editor'));
        saveResult = this.descriptor.save();
        expect(saveResult.nullout).toEqual(['markdown']);
        return expect(saveResult.data).toEqual('xml only');
      });
    });
    describe('advanced editor opens correctly', function() {
      return it('click on advanced editor should work', function() {
        var e;
        loadFixtures('problem-with-markdown.html');
        this.descriptor = new MarkdownEditingDescriptor($('.problem-editor'));
        spyOn(this.descriptor, 'confirmConversionToXml').andReturn(true);
        expect(this.descriptor.confirmConversionToXml).not.toHaveBeenCalled();
        e = jasmine.createSpyObj('e', ['preventDefault']);
        this.descriptor.onShowXMLButton(e);
        expect(e.preventDefault).toHaveBeenCalled();
        expect(this.descriptor.confirmConversionToXml).toHaveBeenCalled();
        return expect($('.editor-bar').length).toEqual(0);
      });
    });
    describe('insertMultipleChoice', function() {
      it('inserts the template if selection is empty', function() {
        var revisedSelection;
        revisedSelection = MarkdownEditingDescriptor.insertMultipleChoice('');
        return expect(revisedSelection).toEqual(MarkdownEditingDescriptor.multipleChoiceTemplate);
      });
      it('wraps existing text', function() {
        var revisedSelection;
        revisedSelection = MarkdownEditingDescriptor.insertMultipleChoice('foo\nbar');
        return expect(revisedSelection).toEqual('( ) foo\n( ) bar\n');
      });
      it('recognizes x as a selection if there is non-whitespace after x', function() {
        var revisedSelection;
        revisedSelection = MarkdownEditingDescriptor.insertMultipleChoice('a\nx b\nc\nx \nd\n x e');
        return expect(revisedSelection).toEqual('( ) a\n(x) b\n( ) c\n( ) x \n( ) d\n(x) e\n');
      });
      it('recognizes x as a selection if it is first non whitespace and has whitespace with other non-whitespace', function() {
        var revisedSelection;
        revisedSelection = MarkdownEditingDescriptor.insertMultipleChoice(' x correct\n x \nex post facto\nb x c\nx c\nxxp');
        return expect(revisedSelection).toEqual('(x) correct\n( )  x \n( ) ex post facto\n( ) b x c\n(x) c\n( ) xxp\n');
      });
      return it('removes multiple newlines but not last one', function() {
        var revisedSelection;
        revisedSelection = MarkdownEditingDescriptor.insertMultipleChoice('a\nx b\n\n\nc\n');
        return expect(revisedSelection).toEqual('( ) a\n(x) b\n( ) c\n');
      });
    });
    describe('insertCheckboxChoice', function() {
      it('inserts the template if selection is empty', function() {
        var revisedSelection;
        revisedSelection = MarkdownEditingDescriptor.insertCheckboxChoice('');
        return expect(revisedSelection).toEqual(MarkdownEditingDescriptor.checkboxChoiceTemplate);
      });
      return it('wraps existing text', function() {
        var revisedSelection;
        revisedSelection = MarkdownEditingDescriptor.insertCheckboxChoice('foo\nbar');
        return expect(revisedSelection).toEqual('[ ] foo\n[ ] bar\n');
      });
    });
    describe('insertStringInput', function() {
      it('inserts the template if selection is empty', function() {
        var revisedSelection;
        revisedSelection = MarkdownEditingDescriptor.insertStringInput('');
        return expect(revisedSelection).toEqual(MarkdownEditingDescriptor.stringInputTemplate);
      });
      return it('wraps existing text', function() {
        var revisedSelection;
        revisedSelection = MarkdownEditingDescriptor.insertStringInput('my text');
        return expect(revisedSelection).toEqual('= my text');
      });
    });
    describe('insertNumberInput', function() {
      it('inserts the template if selection is empty', function() {
        var revisedSelection;
        revisedSelection = MarkdownEditingDescriptor.insertNumberInput('');
        return expect(revisedSelection).toEqual(MarkdownEditingDescriptor.numberInputTemplate);
      });
      return it('wraps existing text', function() {
        var revisedSelection;
        revisedSelection = MarkdownEditingDescriptor.insertNumberInput('my text');
        return expect(revisedSelection).toEqual('= my text');
      });
    });
    describe('insertSelect', function() {
      it('inserts the template if selection is empty', function() {
        var revisedSelection;
        revisedSelection = MarkdownEditingDescriptor.insertSelect('');
        return expect(revisedSelection).toEqual(MarkdownEditingDescriptor.selectTemplate);
      });
      return it('wraps existing text', function() {
        var revisedSelection;
        revisedSelection = MarkdownEditingDescriptor.insertSelect('my text');
        return expect(revisedSelection).toEqual('[[my text]]');
      });
    });
    describe('insertHeader', function() {
      it('inserts the template if selection is empty', function() {
        var revisedSelection;
        revisedSelection = MarkdownEditingDescriptor.insertHeader('');
        return expect(revisedSelection).toEqual(MarkdownEditingDescriptor.headerTemplate);
      });
      return it('wraps existing text', function() {
        var revisedSelection;
        revisedSelection = MarkdownEditingDescriptor.insertHeader('my text');
        return expect(revisedSelection).toEqual('my text\n====\n');
      });
    });
    describe('insertExplanation', function() {
      it('inserts the template if selection is empty', function() {
        var revisedSelection;
        revisedSelection = MarkdownEditingDescriptor.insertExplanation('');
        return expect(revisedSelection).toEqual(MarkdownEditingDescriptor.explanationTemplate);
      });
      return it('wraps existing text', function() {
        var revisedSelection;
        revisedSelection = MarkdownEditingDescriptor.insertExplanation('my text');
        return expect(revisedSelection).toEqual('[explanation]\nmy text\n[explanation]');
      });
    });
    return describe('markdownToXml', function() {
      it('converts raw text to paragraph', function() {
        var data;
        data = MarkdownEditingDescriptor.markdownToXml('foo');
        return expect(data).toEqual('<problem>\n<p>foo</p>\n</problem>');
      });
      it('converts numerical response to xml', function() {
        var data;
        data = MarkdownEditingDescriptor.markdownToXml("A numerical response problem accepts a line of text input from the student, and evaluates the input for correctness based on its numerical value.\n\nThe answer is correct if it is within a specified numerical tolerance of the expected answer.\n\nEnter the numerical value of Pi:\n= 3.14159 +- .02\n\nEnter the approximate value of 502*9:\n= 502*9 +- 15%\n\nEnter the number of fingers on a human hand:\n= 5\n\nRange tolerance case\n= [6, 7]\n= (1, 2)\n\nIf first and last symbols are not brackets, or they are not closed, stringresponse will appear.\n= (7), 7\n= (1+2\n\n[Explanation]\nPi, or the the ratio between a circle's circumference to its diameter, is an irrational number known to extreme precision. It is value is approximately equal to 3.14.\n\nAlthough you can get an exact value by typing 502*9 into a calculator, the result will be close to 500*10, or 5,000. The grader accepts any response within 15% of the true value, 4518, so that you can use any estimation technique that you like.\n\nIf you look at your hand, you can count that you have five fingers.\n[Explanation]");
        return expect(data).toEqual("<problem>\n<p>A numerical response problem accepts a line of text input from the student, and evaluates the input for correctness based on its numerical value.</p>\n\n<p>The answer is correct if it is within a specified numerical tolerance of the expected answer.</p>\n\n<p>Enter the numerical value of Pi:</p>\n<numericalresponse answer=\"3.14159\">\n  <responseparam type=\"tolerance\" default=\".02\" />\n  <formulaequationinput />\n</numericalresponse>\n\n<p>Enter the approximate value of 502*9:</p>\n<numericalresponse answer=\"502*9\">\n  <responseparam type=\"tolerance\" default=\"15%\" />\n  <formulaequationinput />\n</numericalresponse>\n\n<p>Enter the number of fingers on a human hand:</p>\n<numericalresponse answer=\"5\">\n  <formulaequationinput />\n</numericalresponse>\n\n<p>Range tolerance case</p>\n<numericalresponse answer=\"[6, 7]\">\n  <formulaequationinput />\n</numericalresponse>\n<numericalresponse answer=\"(1, 2)\">\n  <formulaequationinput />\n</numericalresponse>\n\n<p>If first and last symbols are not brackets, or they are not closed, stringresponse will appear.</p>\n<stringresponse answer=\"(7), 7\" type=\"ci\" >\n  <textline size=\"20\"/>\n</stringresponse>\n<stringresponse answer=\"(1+2\" type=\"ci\" >\n  <textline size=\"20\"/>\n</stringresponse>\n\n<solution>\n<div class=\"detailed-solution\">\n<p>Explanation</p>\n\n<p>Pi, or the the ratio between a circle's circumference to its diameter, is an irrational number known to extreme precision. It is value is approximately equal to 3.14.</p>\n\n<p>Although you can get an exact value by typing 502*9 into a calculator, the result will be close to 500*10, or 5,000. The grader accepts any response within 15% of the true value, 4518, so that you can use any estimation technique that you like.</p>\n\n<p>If you look at your hand, you can count that you have five fingers.</p>\n\n</div>\n</solution>\n</problem>");
      });
      it('will convert 0 as a numerical response (instead of string response)', function() {
        var data;
        data = MarkdownEditingDescriptor.markdownToXml("Enter 0 with a tolerance:\n= 0 +- .02");
        return expect(data).toEqual("<problem>\n<p>Enter 0 with a tolerance:</p>\n<numericalresponse answer=\"0\">\n  <responseparam type=\"tolerance\" default=\".02\" />\n  <formulaequationinput />\n</numericalresponse>\n\n\n</problem>");
      });
      it('markup with multiple answers doesn\'t break numerical response', function() {
        var data;
        data = MarkdownEditingDescriptor.markdownToXml("Enter 1 with a tolerance:\n= 1 +- .02\nor= 2 +- 5%");
        return expect(data).toEqual("<problem>\n<p>Enter 1 with a tolerance:</p>\n<numericalresponse answer=\"1\">\n  <responseparam type=\"tolerance\" default=\".02\" />\n  <formulaequationinput />\n</numericalresponse>\n\n\n</problem>");
      });
      it('converts multiple choice to xml', function() {
        var data;
        data = MarkdownEditingDescriptor.markdownToXml("A multiple choice problem presents radio buttons for student input. Students can only select a single option presented. Multiple Choice questions have been the subject of many areas of research due to the early invention and adoption of bubble sheets.\n\nOne of the main elements that goes into a good multiple choice question is the existence of good distractors. That is, each of the alternate responses presented to the student should be the result of a plausible mistake that a student might make.\n\nWhat Apple device competed with the portable CD player?\n( ) The iPad\n( ) Napster\n(x) The iPod\n( ) The vegetable peeler\n( ) Android\n( ) The Beatles\n\n[Explanation]\nThe release of the iPod allowed consumers to carry their entire music library with them in a format that did not rely on fragile and energy-intensive spinning disks.\n[Explanation]");
        return expect(data).toEqual("<problem>\n<p>A multiple choice problem presents radio buttons for student input. Students can only select a single option presented. Multiple Choice questions have been the subject of many areas of research due to the early invention and adoption of bubble sheets.</p>\n\n<p>One of the main elements that goes into a good multiple choice question is the existence of good distractors. That is, each of the alternate responses presented to the student should be the result of a plausible mistake that a student might make.</p>\n\n<p>What Apple device competed with the portable CD player?</p>\n<multiplechoiceresponse>\n  <choicegroup type=\"MultipleChoice\">\n    <choice correct=\"false\">The iPad</choice>\n    <choice correct=\"false\">Napster</choice>\n    <choice correct=\"true\">The iPod</choice>\n    <choice correct=\"false\">The vegetable peeler</choice>\n    <choice correct=\"false\">Android</choice>\n    <choice correct=\"false\">The Beatles</choice>\n  </choicegroup>\n</multiplechoiceresponse>\n\n<solution>\n<div class=\"detailed-solution\">\n<p>Explanation</p>\n\n<p>The release of the iPod allowed consumers to carry their entire music library with them in a format that did not rely on fragile and energy-intensive spinning disks.</p>\n\n</div>\n</solution>\n</problem>");
      });
      it('converts multiple choice shuffle to xml', function() {
        var data;
        data = MarkdownEditingDescriptor.markdownToXml("A multiple choice problem presents radio buttons for student input. Students can only select a single option presented. Multiple Choice questions have been the subject of many areas of research due to the early invention and adoption of bubble sheets.\n\nOne of the main elements that goes into a good multiple choice question is the existence of good distractors. That is, each of the alternate responses presented to the student should be the result of a plausible mistake that a student might make.\n\nWhat Apple device competed with the portable CD player?\n(!x@) The iPad\n(@) Napster\n() The iPod\n( ) The vegetable peeler\n( ) Android\n(@) The Beatles\n\n[Explanation]\nThe release of the iPod allowed consumers to carry their entire music library with them in a format that did not rely on fragile and energy-intensive spinning disks.\n[Explanation]");
        return expect(data).toEqual("<problem>\n<p>A multiple choice problem presents radio buttons for student input. Students can only select a single option presented. Multiple Choice questions have been the subject of many areas of research due to the early invention and adoption of bubble sheets.</p>\n\n<p>One of the main elements that goes into a good multiple choice question is the existence of good distractors. That is, each of the alternate responses presented to the student should be the result of a plausible mistake that a student might make.</p>\n\n<p>What Apple device competed with the portable CD player?</p>\n<multiplechoiceresponse>\n  <choicegroup type=\"MultipleChoice\" shuffle=\"true\">\n    <choice correct=\"true\" fixed=\"true\">The iPad</choice>\n    <choice correct=\"false\" fixed=\"true\">Napster</choice>\n    <choice correct=\"false\">The iPod</choice>\n    <choice correct=\"false\">The vegetable peeler</choice>\n    <choice correct=\"false\">Android</choice>\n    <choice correct=\"false\" fixed=\"true\">The Beatles</choice>\n  </choicegroup>\n</multiplechoiceresponse>\n\n<solution>\n<div class=\"detailed-solution\">\n<p>Explanation</p>\n\n<p>The release of the iPod allowed consumers to carry their entire music library with them in a format that did not rely on fragile and energy-intensive spinning disks.</p>\n\n</div>\n</solution>\n</problem>");
      });
      it('converts a series of multiplechoice to xml', function() {
        var data;
        data = MarkdownEditingDescriptor.markdownToXml("bleh\n(!x) a\n() b\n() c\nyatta\n( ) x\n( ) y\n(x) z\ntesta\n(!) i\n( ) ii\n(x) iii\n[Explanation]\nWhen the student is ready, the explanation appears.\n[Explanation]");
        return expect(data).toEqual("<problem>\n<p>bleh</p>\n<multiplechoiceresponse>\n  <choicegroup type=\"MultipleChoice\" shuffle=\"true\">\n    <choice correct=\"true\">a</choice>\n    <choice correct=\"false\">b</choice>\n    <choice correct=\"false\">c</choice>\n  </choicegroup>\n</multiplechoiceresponse>\n\n<p>yatta</p>\n<multiplechoiceresponse>\n  <choicegroup type=\"MultipleChoice\">\n    <choice correct=\"false\">x</choice>\n    <choice correct=\"false\">y</choice>\n    <choice correct=\"true\">z</choice>\n  </choicegroup>\n</multiplechoiceresponse>\n\n<p>testa</p>\n<multiplechoiceresponse>\n  <choicegroup type=\"MultipleChoice\" shuffle=\"true\">\n    <choice correct=\"false\">i</choice>\n    <choice correct=\"false\">ii</choice>\n    <choice correct=\"true\">iii</choice>\n  </choicegroup>\n</multiplechoiceresponse>\n\n<solution>\n<div class=\"detailed-solution\">\n<p>Explanation</p>\n\n<p>When the student is ready, the explanation appears.</p>\n\n</div>\n</solution>\n</problem>");
      });
      it('converts OptionResponse to xml', function() {
        var data;
        data = MarkdownEditingDescriptor.markdownToXml("OptionResponse gives a limited set of options for students to respond with, and presents those options in a format that encourages them to search for a specific answer rather than being immediately presented with options from which to recognize the correct answer.\n\nThe answer options and the identification of the correct answer is defined in the <b>optioninput</b> tag.\n\nTranslation between Option Response and __________ is extremely straightforward:\n[[(Multiple Choice), String Response, Numerical Response, External Response, Image Response]]\n\n[Explanation]\nMultiple Choice also allows students to select from a variety of pre-written responses, although the format makes it easier for students to read very long response options. Optionresponse also differs slightly because students are more likely to think of an answer and then search for it rather than relying purely on recognition to answer the question.\n[Explanation]");
        return expect(data).toEqual("<problem>\n<p>OptionResponse gives a limited set of options for students to respond with, and presents those options in a format that encourages them to search for a specific answer rather than being immediately presented with options from which to recognize the correct answer.</p>\n\n<p>The answer options and the identification of the correct answer is defined in the <b>optioninput</b> tag.</p>\n\n<p>Translation between Option Response and __________ is extremely straightforward:</p>\n\n<optionresponse>\n  <optioninput options=\"('Multiple Choice','String Response','Numerical Response','External Response','Image Response')\" correct=\"Multiple Choice\"></optioninput>\n</optionresponse>\n\n<solution>\n<div class=\"detailed-solution\">\n<p>Explanation</p>\n\n<p>Multiple Choice also allows students to select from a variety of pre-written responses, although the format makes it easier for students to read very long response options. Optionresponse also differs slightly because students are more likely to think of an answer and then search for it rather than relying purely on recognition to answer the question.</p>\n\n</div>\n</solution>\n</problem>");
      });
      it('converts StringResponse to xml', function() {
        var data;
        data = MarkdownEditingDescriptor.markdownToXml("A string response problem accepts a line of text input from the student, and evaluates the input for correctness based on an expected answer within each input box.\n\nThe answer is correct if it matches every character of the expected answer. This can be a problem with international spelling, dates, or anything where the format of the answer is not clear.\n\nWhich US state has Lansing as its capital?\n= Michigan\n\n[Explanation]\nLansing is the capital of Michigan, although it is not Michgan's largest city, or even the seat of the county in which it resides.\n[Explanation]");
        return expect(data).toEqual("<problem>\n<p>A string response problem accepts a line of text input from the student, and evaluates the input for correctness based on an expected answer within each input box.</p>\n\n<p>The answer is correct if it matches every character of the expected answer. This can be a problem with international spelling, dates, or anything where the format of the answer is not clear.</p>\n\n<p>Which US state has Lansing as its capital?</p>\n<stringresponse answer=\"Michigan\" type=\"ci\" >\n  <textline size=\"20\"/>\n</stringresponse>\n\n<solution>\n<div class=\"detailed-solution\">\n<p>Explanation</p>\n\n<p>Lansing is the capital of Michigan, although it is not Michgan's largest city, or even the seat of the county in which it resides.</p>\n\n</div>\n</solution>\n</problem>");
      });
      it('converts StringResponse with regular expression to xml', function() {
        var data;
        data = MarkdownEditingDescriptor.markdownToXml("Who lead the civil right movement in the United States of America?\n= | \w*\.?\s*Luther King\s*.*\n\n[Explanation]\nTest Explanation.\n[Explanation]");
        return expect(data).toEqual("<problem>\n<p>Who lead the civil right movement in the United States of America?</p>\n<stringresponse answer=\"\w*\.?\s*Luther King\s*.*\" type=\"ci regexp\" >\n  <textline size=\"20\"/>\n</stringresponse>\n\n<solution>\n<div class=\"detailed-solution\">\n<p>Explanation</p>\n\n<p>Test Explanation.</p>\n\n</div>\n</solution>\n</problem>");
      });
      it('converts StringResponse with multiple answers to xml', function() {
        var data;
        data = MarkdownEditingDescriptor.markdownToXml("Who lead the civil right movement in the United States of America?\n= Dr. Martin Luther King Jr.\nor= Doctor Martin Luther King Junior\nor= Martin Luther King\nor= Martin Luther King Junior\n\n[Explanation]\nTest Explanation.\n[Explanation]");
        return expect(data).toEqual("<problem>\n<p>Who lead the civil right movement in the United States of America?</p>\n<stringresponse answer=\"Dr. Martin Luther King Jr.\" type=\"ci\" >\n  <additional_answer>Doctor Martin Luther King Junior</additional_answer>\n  <additional_answer>Martin Luther King</additional_answer>\n  <additional_answer>Martin Luther King Junior</additional_answer>\n  <textline size=\"20\"/>\n</stringresponse>\n\n<solution>\n<div class=\"detailed-solution\">\n<p>Explanation</p>\n\n<p>Test Explanation.</p>\n\n</div>\n</solution>\n</problem>");
      });
      it('converts StringResponse with multiple answers and regular expressions to xml', function() {
        var data;
        data = MarkdownEditingDescriptor.markdownToXml("Write a number from 1 to 4.\n=| ^One$\nor= two\nor= ^thre+\nor= ^4|Four$\n\n[Explanation]\nTest Explanation.\n[Explanation]");
        return expect(data).toEqual("<problem>\n<p>Write a number from 1 to 4.</p>\n<stringresponse answer=\"^One$\" type=\"ci regexp\" >\n  <additional_answer>two</additional_answer>\n  <additional_answer>^thre+</additional_answer>\n  <additional_answer>^4|Four$</additional_answer>\n  <textline size=\"20\"/>\n</stringresponse>\n\n<solution>\n<div class=\"detailed-solution\">\n<p>Explanation</p>\n\n<p>Test Explanation.</p>\n\n</div>\n</solution>\n</problem>");
      });
      it('converts markdown labels to label attributes', function() {
        var data;
        data = MarkdownEditingDescriptor.markdownToXml(">>Who lead the civil right movement in the United States of America?<<\n= | \w*\.?\s*Luther King\s*.*\n\n[Explanation]\nTest Explanation.\n[Explanation]");
        return expect(data).toEqual("<problem>\n<p>Who lead the civil right movement in the United States of America?</p>\n<stringresponse answer=\"w*.?s*Luther Kings*.*\" type=\"ci regexp\" >\n  <textline label=\"Who lead the civil right movement in the United States of America?\" size=\"20\"/>\n</stringresponse>\n\n<solution>\n<div class=\"detailed-solution\">\n<p>Explanation</p>\n\n<p>Test Explanation.</p>\n\n</div>\n</solution>\n</problem>");
      });
      it('handles multiple questions with labels', function() {
        var data;
        data = MarkdownEditingDescriptor.markdownToXml("France is a country in Europe.\n\n>>What is the capital of France?<<\n= Paris\n\nGermany is a country in Europe, too.\n\n>>What is the capital of Germany?<<\n( ) Bonn\n( ) Hamburg\n(x) Berlin\n( ) Donut");
        return expect(data).toEqual("<problem>\n<p>France is a country in Europe.</p>\n\n<p>What is the capital of France?</p>\n<stringresponse answer=\"Paris\" type=\"ci\" >\n  <textline label=\"What is the capital of France?\" size=\"20\"/>\n</stringresponse>\n\n<p>Germany is a country in Europe, too.</p>\n\n<p>What is the capital of Germany?</p>\n<multiplechoiceresponse>\n  <choicegroup label=\"What is the capital of Germany?\" type=\"MultipleChoice\">\n    <choice correct=\"false\">Bonn</choice>\n    <choice correct=\"false\">Hamburg</choice>\n    <choice correct=\"true\">Berlin</choice>\n    <choice correct=\"false\">Donut</choice>\n  </choicegroup>\n</multiplechoiceresponse>\n\n\n</problem>");
      });
      it('tests multiple questions with only one label', function() {
        var data;
        data = MarkdownEditingDescriptor.markdownToXml("France is a country in Europe.\n\n>>What is the capital of France?<<\n= Paris\n\nGermany is a country in Europe, too.\n\nWhat is the capital of Germany?\n( ) Bonn\n( ) Hamburg\n(x) Berlin\n( ) Donut");
        return expect(data).toEqual("<problem>\n<p>France is a country in Europe.</p>\n\n<p>What is the capital of France?</p>\n<stringresponse answer=\"Paris\" type=\"ci\" >\n  <textline label=\"What is the capital of France?\" size=\"20\"/>\n</stringresponse>\n\n<p>Germany is a country in Europe, too.</p>\n\n<p>What is the capital of Germany?</p>\n<multiplechoiceresponse>\n  <choicegroup type=\"MultipleChoice\">\n    <choice correct=\"false\">Bonn</choice>\n    <choice correct=\"false\">Hamburg</choice>\n    <choice correct=\"true\">Berlin</choice>\n    <choice correct=\"false\">Donut</choice>\n  </choicegroup>\n</multiplechoiceresponse>\n\n\n</problem>");
      });
      it('tests malformed labels', function() {
        var data;
        data = MarkdownEditingDescriptor.markdownToXml("France is a country in Europe.\n\n>>What is the capital of France?<\n= Paris\n\nblah>>What is the capital of <<Germany?<<\n( ) Bonn\n( ) Hamburg\n(x) Berlin\n( ) Donut");
        return expect(data).toEqual("<problem>\n<p>France is a country in Europe.</p>\n\n<p>>>What is the capital of France?<</p>\n<stringresponse answer=\"Paris\" type=\"ci\" >\n  <textline size=\"20\"/>\n</stringresponse>\n\n<p>blahWhat is the capital of Germany?</p>\n<multiplechoiceresponse>\n  <choicegroup label=\"What is the capital of &lt;&lt;Germany?\" type=\"MultipleChoice\">\n    <choice correct=\"false\">Bonn</choice>\n    <choice correct=\"false\">Hamburg</choice>\n    <choice correct=\"true\">Berlin</choice>\n    <choice correct=\"false\">Donut</choice>\n  </choicegroup>\n</multiplechoiceresponse>\n\n\n</problem>");
      });
      it('adds labels to formulae', function() {
        var data;
        data = MarkdownEditingDescriptor.markdownToXml(">>Enter the numerical value of Pi:<<\n= 3.14159 +- .02");
        return expect(data).toEqual("<problem>\n<p>Enter the numerical value of Pi:</p>\n<numericalresponse answer=\"3.14159\">\n  <responseparam type=\"tolerance\" default=\".02\" />\n  <formulaequationinput label=\"Enter the numerical value of Pi:\" />\n</numericalresponse>\n\n\n</problem>");
      });
      it('escapes entities in labels', function() {
        var data;
        data = MarkdownEditingDescriptor.markdownToXml(">>What is the \"capital\" of France & the 'best' > place < to live\"?<<\n= Paris");
        return expect(data).toEqual("<problem>\n<p>What is the \"capital\" of France & the 'best' > place < to live\"?</p>\n<stringresponse answer=\"Paris\" type=\"ci\" >\n  <textline label=\"What is the &quot;capital&quot; of France &amp; the &apos;best&apos; &gt; place &lt; to live&quot;?\" size=\"20\"/>\n</stringresponse>\n\n\n</problem>");
      });
      return it('converts headers and oddities to xml', function() {
        var data;
        data = MarkdownEditingDescriptor.markdownToXml("Not a header\nA header\n==============\n\nMultiple choice w/ parentheticals\n( ) option (with parens)\n( ) xd option (x)\n()) parentheses inside\n() no space b4 close paren\n\nChoice checks\n[ ] option1 [x]\n[x] correct\n[x] redundant\n[(] distractor\n[] no space\n\nOption with multiple correct ones\n[[one option, (correct one), (should not be correct)]]\n\nOption with embedded parens\n[[My (heart), another, (correct)]]\n\nWhat happens w/ empty correct options?\n[[()]]\n\n[Explanation]see[/expLanation]\n\n[explanation]\norphaned start\n\nNo p tags in the below\n<script type='javascript'>\n   var two = 2;\n\n   console.log(two * 2);\n</script>\n\nBut in this there should be\n<div>\nGreat ideas require offsetting.\n\nbad tests require drivel\n</div>\n\n[code]\nCode should be nicely monospaced.\n[/code]");
        return expect(data).toEqual("<problem>\n<p>Not a header</p>\n<h1>A header</h1>\n\n<p>Multiple choice w/ parentheticals</p>\n<multiplechoiceresponse>\n  <choicegroup type=\"MultipleChoice\">\n    <choice correct=\"false\">option (with parens)</choice>\n    <choice correct=\"false\">xd option (x)</choice>\n    <choice correct=\"false\">parentheses inside</choice>\n    <choice correct=\"false\">no space b4 close paren</choice>\n  </choicegroup>\n</multiplechoiceresponse>\n\n<p>Choice checks</p>\n<choiceresponse>\n  <checkboxgroup direction=\"vertical\">\n    <choice correct=\"false\">option1 [x]</choice>\n    <choice correct=\"true\">correct</choice>\n    <choice correct=\"true\">redundant</choice>\n    <choice correct=\"false\">distractor</choice>\n    <choice correct=\"false\">no space</choice>\n  </checkboxgroup>\n</choiceresponse>\n\n<p>Option with multiple correct ones</p>\n\n<optionresponse>\n  <optioninput options=\"('one option','correct one','should not be correct')\" correct=\"correct one\"></optioninput>\n</optionresponse>\n\n<p>Option with embedded parens</p>\n\n<optionresponse>\n  <optioninput options=\"('My (heart)','another','correct')\" correct=\"correct\"></optioninput>\n</optionresponse>\n\n<p>What happens w/ empty correct options?</p>\n\n<optionresponse>\n  <optioninput options=\"('')\" correct=\"\"></optioninput>\n</optionresponse>\n\n<solution>\n<div class=\"detailed-solution\">\n<p>Explanation</p>\n\n<p>see</p>\n</div>\n</solution>\n\n<p>[explanation]</p>\n<p>orphaned start</p>\n\n<p>No p tags in the below</p>\n<script type='javascript'>\n   var two = 2;\n\n   console.log(two * 2);\n</script>\n\n<p>But in this there should be</p>\n<div>\n<p>Great ideas require offsetting.</p>\n\n<p>bad tests require drivel</p>\n</div>\n\n<pre><code>\nCode should be nicely monospaced.\n</code></pre>\n</problem>");
      });
    });
  });

}).call(this);
